title: "Mekki TORABIE"
author: "MEILLEURE GUÉRISSEUR ÉNERGÉTIQUE"
description: "MEILLEURE GUÉRISSEUR ÉNERGÉTIQUE"
more: "lire plus »"
baseurl: "/contrast/"
paginate: 3
permalink: pretty
excerpt_separator: "\n\n\n" # two blank lines

style:
  minimalist: false
  dark: false

navigation:
  - index.html
  - about.md
  - archive.html
  

comments:
  disqus: "disqus-contrast"
#  isso: "comments.mysite.org"

links: # see http://fontawesome.io/icons/#brand for all possible icons
  - envelope: "mekitourabi@gmail.com"
  - facebook: "https://www.facebook.com/profile.php?id=100012436140076"

defaults: [{scope: {path: ""}, values: {layout: "default"}}, {scope: {path: "", type: "posts"}, values: {comments: true}}]
sass: {style: expanded}
plugins: [jekyll-feed, jekyll-paginate]
